# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/shiobara/Documents/jogotecprog

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/shiobara/Documents/jogotecprog

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shiobara/Documents/jogotecprog/CMakeFiles /Users/shiobara/Documents/jogotecprog//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/shiobara/Documents/jogotecprog/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

src/Animation.o: src/Animation.cpp.o
.PHONY : src/Animation.o

# target to build an object file
src/Animation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Animation.cpp.o
.PHONY : src/Animation.cpp.o

src/Animation.i: src/Animation.cpp.i
.PHONY : src/Animation.i

# target to preprocess a source file
src/Animation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Animation.cpp.i
.PHONY : src/Animation.cpp.i

src/Animation.s: src/Animation.cpp.s
.PHONY : src/Animation.s

# target to generate assembly for a file
src/Animation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Animation.cpp.s
.PHONY : src/Animation.cpp.s

src/Arvore.o: src/Arvore.cpp.o
.PHONY : src/Arvore.o

# target to build an object file
src/Arvore.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Arvore.cpp.o
.PHONY : src/Arvore.cpp.o

src/Arvore.i: src/Arvore.cpp.i
.PHONY : src/Arvore.i

# target to preprocess a source file
src/Arvore.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Arvore.cpp.i
.PHONY : src/Arvore.cpp.i

src/Arvore.s: src/Arvore.cpp.s
.PHONY : src/Arvore.s

# target to generate assembly for a file
src/Arvore.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Arvore.cpp.s
.PHONY : src/Arvore.cpp.s

src/Demonio.o: src/Demonio.cpp.o
.PHONY : src/Demonio.o

# target to build an object file
src/Demonio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Demonio.cpp.o
.PHONY : src/Demonio.cpp.o

src/Demonio.i: src/Demonio.cpp.i
.PHONY : src/Demonio.i

# target to preprocess a source file
src/Demonio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Demonio.cpp.i
.PHONY : src/Demonio.cpp.i

src/Demonio.s: src/Demonio.cpp.s
.PHONY : src/Demonio.s

# target to generate assembly for a file
src/Demonio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Demonio.cpp.s
.PHONY : src/Demonio.cpp.s

src/Ente.o: src/Ente.cpp.o
.PHONY : src/Ente.o

# target to build an object file
src/Ente.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Ente.cpp.o
.PHONY : src/Ente.cpp.o

src/Ente.i: src/Ente.cpp.i
.PHONY : src/Ente.i

# target to preprocess a source file
src/Ente.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Ente.cpp.i
.PHONY : src/Ente.cpp.i

src/Ente.s: src/Ente.cpp.s
.PHONY : src/Ente.s

# target to generate assembly for a file
src/Ente.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Ente.cpp.s
.PHONY : src/Ente.cpp.s

src/Entidade.o: src/Entidade.cpp.o
.PHONY : src/Entidade.o

# target to build an object file
src/Entidade.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Entidade.cpp.o
.PHONY : src/Entidade.cpp.o

src/Entidade.i: src/Entidade.cpp.i
.PHONY : src/Entidade.i

# target to preprocess a source file
src/Entidade.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Entidade.cpp.i
.PHONY : src/Entidade.cpp.i

src/Entidade.s: src/Entidade.cpp.s
.PHONY : src/Entidade.s

# target to generate assembly for a file
src/Entidade.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Entidade.cpp.s
.PHONY : src/Entidade.cpp.s

src/Fase.o: src/Fase.cpp.o
.PHONY : src/Fase.o

# target to build an object file
src/Fase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Fase.cpp.o
.PHONY : src/Fase.cpp.o

src/Fase.i: src/Fase.cpp.i
.PHONY : src/Fase.i

# target to preprocess a source file
src/Fase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Fase.cpp.i
.PHONY : src/Fase.cpp.i

src/Fase.s: src/Fase.cpp.s
.PHONY : src/Fase.s

# target to generate assembly for a file
src/Fase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Fase.cpp.s
.PHONY : src/Fase.cpp.s

src/FasePrimeira.o: src/FasePrimeira.cpp.o
.PHONY : src/FasePrimeira.o

# target to build an object file
src/FasePrimeira.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/FasePrimeira.cpp.o
.PHONY : src/FasePrimeira.cpp.o

src/FasePrimeira.i: src/FasePrimeira.cpp.i
.PHONY : src/FasePrimeira.i

# target to preprocess a source file
src/FasePrimeira.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/FasePrimeira.cpp.i
.PHONY : src/FasePrimeira.cpp.i

src/FasePrimeira.s: src/FasePrimeira.cpp.s
.PHONY : src/FasePrimeira.s

# target to generate assembly for a file
src/FasePrimeira.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/FasePrimeira.cpp.s
.PHONY : src/FasePrimeira.cpp.s

src/GerenciadorColisoes.o: src/GerenciadorColisoes.cpp.o
.PHONY : src/GerenciadorColisoes.o

# target to build an object file
src/GerenciadorColisoes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GerenciadorColisoes.cpp.o
.PHONY : src/GerenciadorColisoes.cpp.o

src/GerenciadorColisoes.i: src/GerenciadorColisoes.cpp.i
.PHONY : src/GerenciadorColisoes.i

# target to preprocess a source file
src/GerenciadorColisoes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GerenciadorColisoes.cpp.i
.PHONY : src/GerenciadorColisoes.cpp.i

src/GerenciadorColisoes.s: src/GerenciadorColisoes.cpp.s
.PHONY : src/GerenciadorColisoes.s

# target to generate assembly for a file
src/GerenciadorColisoes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GerenciadorColisoes.cpp.s
.PHONY : src/GerenciadorColisoes.cpp.s

src/GerenciadorGrafico.o: src/GerenciadorGrafico.cpp.o
.PHONY : src/GerenciadorGrafico.o

# target to build an object file
src/GerenciadorGrafico.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GerenciadorGrafico.cpp.o
.PHONY : src/GerenciadorGrafico.cpp.o

src/GerenciadorGrafico.i: src/GerenciadorGrafico.cpp.i
.PHONY : src/GerenciadorGrafico.i

# target to preprocess a source file
src/GerenciadorGrafico.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GerenciadorGrafico.cpp.i
.PHONY : src/GerenciadorGrafico.cpp.i

src/GerenciadorGrafico.s: src/GerenciadorGrafico.cpp.s
.PHONY : src/GerenciadorGrafico.s

# target to generate assembly for a file
src/GerenciadorGrafico.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/GerenciadorGrafico.cpp.s
.PHONY : src/GerenciadorGrafico.cpp.s

src/Inimigo.o: src/Inimigo.cpp.o
.PHONY : src/Inimigo.o

# target to build an object file
src/Inimigo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Inimigo.cpp.o
.PHONY : src/Inimigo.cpp.o

src/Inimigo.i: src/Inimigo.cpp.i
.PHONY : src/Inimigo.i

# target to preprocess a source file
src/Inimigo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Inimigo.cpp.i
.PHONY : src/Inimigo.cpp.i

src/Inimigo.s: src/Inimigo.cpp.s
.PHONY : src/Inimigo.s

# target to generate assembly for a file
src/Inimigo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Inimigo.cpp.s
.PHONY : src/Inimigo.cpp.s

src/Jogador.o: src/Jogador.cpp.o
.PHONY : src/Jogador.o

# target to build an object file
src/Jogador.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Jogador.cpp.o
.PHONY : src/Jogador.cpp.o

src/Jogador.i: src/Jogador.cpp.i
.PHONY : src/Jogador.i

# target to preprocess a source file
src/Jogador.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Jogador.cpp.i
.PHONY : src/Jogador.cpp.i

src/Jogador.s: src/Jogador.cpp.s
.PHONY : src/Jogador.s

# target to generate assembly for a file
src/Jogador.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Jogador.cpp.s
.PHONY : src/Jogador.cpp.s

src/Jogo.o: src/Jogo.cpp.o
.PHONY : src/Jogo.o

# target to build an object file
src/Jogo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Jogo.cpp.o
.PHONY : src/Jogo.cpp.o

src/Jogo.i: src/Jogo.cpp.i
.PHONY : src/Jogo.i

# target to preprocess a source file
src/Jogo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Jogo.cpp.i
.PHONY : src/Jogo.cpp.i

src/Jogo.s: src/Jogo.cpp.s
.PHONY : src/Jogo.s

# target to generate assembly for a file
src/Jogo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Jogo.cpp.s
.PHONY : src/Jogo.cpp.s

src/Limites.o: src/Limites.cpp.o
.PHONY : src/Limites.o

# target to build an object file
src/Limites.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Limites.cpp.o
.PHONY : src/Limites.cpp.o

src/Limites.i: src/Limites.cpp.i
.PHONY : src/Limites.i

# target to preprocess a source file
src/Limites.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Limites.cpp.i
.PHONY : src/Limites.cpp.i

src/Limites.s: src/Limites.cpp.s
.PHONY : src/Limites.s

# target to generate assembly for a file
src/Limites.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Limites.cpp.s
.PHONY : src/Limites.cpp.s

src/ListaEntidades.o: src/ListaEntidades.cpp.o
.PHONY : src/ListaEntidades.o

# target to build an object file
src/ListaEntidades.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ListaEntidades.cpp.o
.PHONY : src/ListaEntidades.cpp.o

src/ListaEntidades.i: src/ListaEntidades.cpp.i
.PHONY : src/ListaEntidades.i

# target to preprocess a source file
src/ListaEntidades.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ListaEntidades.cpp.i
.PHONY : src/ListaEntidades.cpp.i

src/ListaEntidades.s: src/ListaEntidades.cpp.s
.PHONY : src/ListaEntidades.s

# target to generate assembly for a file
src/ListaEntidades.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ListaEntidades.cpp.s
.PHONY : src/ListaEntidades.cpp.s

src/Morte.o: src/Morte.cpp.o
.PHONY : src/Morte.o

# target to build an object file
src/Morte.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Morte.cpp.o
.PHONY : src/Morte.cpp.o

src/Morte.i: src/Morte.cpp.i
.PHONY : src/Morte.i

# target to preprocess a source file
src/Morte.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Morte.cpp.i
.PHONY : src/Morte.cpp.i

src/Morte.s: src/Morte.cpp.s
.PHONY : src/Morte.s

# target to generate assembly for a file
src/Morte.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Morte.cpp.s
.PHONY : src/Morte.cpp.s

src/Obst_Medio.o: src/Obst_Medio.cpp.o
.PHONY : src/Obst_Medio.o

# target to build an object file
src/Obst_Medio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Obst_Medio.cpp.o
.PHONY : src/Obst_Medio.cpp.o

src/Obst_Medio.i: src/Obst_Medio.cpp.i
.PHONY : src/Obst_Medio.i

# target to preprocess a source file
src/Obst_Medio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Obst_Medio.cpp.i
.PHONY : src/Obst_Medio.cpp.i

src/Obst_Medio.s: src/Obst_Medio.cpp.s
.PHONY : src/Obst_Medio.s

# target to generate assembly for a file
src/Obst_Medio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Obst_Medio.cpp.s
.PHONY : src/Obst_Medio.cpp.s

src/Obstaculo.o: src/Obstaculo.cpp.o
.PHONY : src/Obstaculo.o

# target to build an object file
src/Obstaculo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Obstaculo.cpp.o
.PHONY : src/Obstaculo.cpp.o

src/Obstaculo.i: src/Obstaculo.cpp.i
.PHONY : src/Obstaculo.i

# target to preprocess a source file
src/Obstaculo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Obstaculo.cpp.i
.PHONY : src/Obstaculo.cpp.i

src/Obstaculo.s: src/Obstaculo.cpp.s
.PHONY : src/Obstaculo.s

# target to generate assembly for a file
src/Obstaculo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Obstaculo.cpp.s
.PHONY : src/Obstaculo.cpp.s

src/Personagem.o: src/Personagem.cpp.o
.PHONY : src/Personagem.o

# target to build an object file
src/Personagem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Personagem.cpp.o
.PHONY : src/Personagem.cpp.o

src/Personagem.i: src/Personagem.cpp.i
.PHONY : src/Personagem.i

# target to preprocess a source file
src/Personagem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Personagem.cpp.i
.PHONY : src/Personagem.cpp.i

src/Personagem.s: src/Personagem.cpp.s
.PHONY : src/Personagem.s

# target to generate assembly for a file
src/Personagem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Personagem.cpp.s
.PHONY : src/Personagem.cpp.s

src/Plataforma.o: src/Plataforma.cpp.o
.PHONY : src/Plataforma.o

# target to build an object file
src/Plataforma.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Plataforma.cpp.o
.PHONY : src/Plataforma.cpp.o

src/Plataforma.i: src/Plataforma.cpp.i
.PHONY : src/Plataforma.i

# target to preprocess a source file
src/Plataforma.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Plataforma.cpp.i
.PHONY : src/Plataforma.cpp.i

src/Plataforma.s: src/Plataforma.cpp.s
.PHONY : src/Plataforma.s

# target to generate assembly for a file
src/Plataforma.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Plataforma.cpp.s
.PHONY : src/Plataforma.cpp.s

src/Projetil.o: src/Projetil.cpp.o
.PHONY : src/Projetil.o

# target to build an object file
src/Projetil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Projetil.cpp.o
.PHONY : src/Projetil.cpp.o

src/Projetil.i: src/Projetil.cpp.i
.PHONY : src/Projetil.i

# target to preprocess a source file
src/Projetil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Projetil.cpp.i
.PHONY : src/Projetil.cpp.i

src/Projetil.s: src/Projetil.cpp.s
.PHONY : src/Projetil.s

# target to generate assembly for a file
src/Projetil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Projetil.cpp.s
.PHONY : src/Projetil.cpp.s

src/SingleFrameAnimation.o: src/SingleFrameAnimation.cpp.o
.PHONY : src/SingleFrameAnimation.o

# target to build an object file
src/SingleFrameAnimation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SingleFrameAnimation.cpp.o
.PHONY : src/SingleFrameAnimation.cpp.o

src/SingleFrameAnimation.i: src/SingleFrameAnimation.cpp.i
.PHONY : src/SingleFrameAnimation.i

# target to preprocess a source file
src/SingleFrameAnimation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SingleFrameAnimation.cpp.i
.PHONY : src/SingleFrameAnimation.cpp.i

src/SingleFrameAnimation.s: src/SingleFrameAnimation.cpp.s
.PHONY : src/SingleFrameAnimation.s

# target to generate assembly for a file
src/SingleFrameAnimation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/SingleFrameAnimation.cpp.s
.PHONY : src/SingleFrameAnimation.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... main"
	@echo "... src/Animation.o"
	@echo "... src/Animation.i"
	@echo "... src/Animation.s"
	@echo "... src/Arvore.o"
	@echo "... src/Arvore.i"
	@echo "... src/Arvore.s"
	@echo "... src/Demonio.o"
	@echo "... src/Demonio.i"
	@echo "... src/Demonio.s"
	@echo "... src/Ente.o"
	@echo "... src/Ente.i"
	@echo "... src/Ente.s"
	@echo "... src/Entidade.o"
	@echo "... src/Entidade.i"
	@echo "... src/Entidade.s"
	@echo "... src/Fase.o"
	@echo "... src/Fase.i"
	@echo "... src/Fase.s"
	@echo "... src/FasePrimeira.o"
	@echo "... src/FasePrimeira.i"
	@echo "... src/FasePrimeira.s"
	@echo "... src/GerenciadorColisoes.o"
	@echo "... src/GerenciadorColisoes.i"
	@echo "... src/GerenciadorColisoes.s"
	@echo "... src/GerenciadorGrafico.o"
	@echo "... src/GerenciadorGrafico.i"
	@echo "... src/GerenciadorGrafico.s"
	@echo "... src/Inimigo.o"
	@echo "... src/Inimigo.i"
	@echo "... src/Inimigo.s"
	@echo "... src/Jogador.o"
	@echo "... src/Jogador.i"
	@echo "... src/Jogador.s"
	@echo "... src/Jogo.o"
	@echo "... src/Jogo.i"
	@echo "... src/Jogo.s"
	@echo "... src/Limites.o"
	@echo "... src/Limites.i"
	@echo "... src/Limites.s"
	@echo "... src/ListaEntidades.o"
	@echo "... src/ListaEntidades.i"
	@echo "... src/ListaEntidades.s"
	@echo "... src/Morte.o"
	@echo "... src/Morte.i"
	@echo "... src/Morte.s"
	@echo "... src/Obst_Medio.o"
	@echo "... src/Obst_Medio.i"
	@echo "... src/Obst_Medio.s"
	@echo "... src/Obstaculo.o"
	@echo "... src/Obstaculo.i"
	@echo "... src/Obstaculo.s"
	@echo "... src/Personagem.o"
	@echo "... src/Personagem.i"
	@echo "... src/Personagem.s"
	@echo "... src/Plataforma.o"
	@echo "... src/Plataforma.i"
	@echo "... src/Plataforma.s"
	@echo "... src/Projetil.o"
	@echo "... src/Projetil.i"
	@echo "... src/Projetil.s"
	@echo "... src/SingleFrameAnimation.o"
	@echo "... src/SingleFrameAnimation.i"
	@echo "... src/SingleFrameAnimation.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

